@baseUrl = http://localhost:3001


GET {{baseUrl}}

### 

GET {{baseUrl}}/accounts

### 

### 

POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "cpf": "123456789",
  "name": "Angelo Rafael"
}