@baseUrl = http://localhost:3001


GET {{baseUrl}}

### 

GET {{baseUrl}}/accounts

### 

### 

POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "cpf": "123456789",
  "name": "Angelo Rafael"
}


### 

GET {{baseUrl}}/statements
CPF: 123456789


### 

POST {{baseUrl}}/deposit
Content-Type: application/json
CPF: 123456789

{
  "description": "Depósito do Ignite",
  "amount": 1500.00
}

### 

POST {{baseUrl}}/withdraw
Content-Type: application/json
CPF: 123456789

{
  "amount": 100
}
