@baseUrl = http://localhost:3000


GET {{baseUrl}}

### 

GET {{baseUrl}}/accounts/all

### 

GET {{baseUrl}}/accounts
CPF: 123456789

### 

POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "cpf": "123456789",
  "name": "Angelo Rafael"
}

###

PUT {{baseUrl}}/accounts
CPF: 123456789
Content-Type: application/json

{
  "name": "Mario Souto"
}

